# Generated by Django 5.1.5 on 2025-01-22 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_product_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='buy',
            name='size',
            field=models.ForeignKey(default='quantity', on_delete=django.db.models.deletion.CASCADE, to='app.size'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.ForeignKey(default='quantity', on_delete=django.db.models.deletion.CASCADE, to='app.size'),
            preserve_default=False,
        ),
    ]
