# Generated by Django 5.1.5 on 2025-01-22 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
